### ISSUE TITLE
2nd generation paths wear leading slashes where 1st generation don't

### ISSUE THREAD

**Issue by hiddenalpha** [swisspush/apikana#20]
The 2nd generation Paths (as in: com.example.mypackage.MyPackagePaths) now include a leading slash where 1st generation paths (as in: com.example.mypackage.Paths) don't.

In PAISA (Project where apikana was born??) in [Alice Library](https://wikit.post.ch/x/hoGuD) is defined:

> These URLs also include the context path (always with trailing slash), i.e. the service name as first path element. E.g: http://example.com:1234/eagle/, http://example.com:1234/saturn/

Now as soon services migrating to 2nd gen paths they'll get in trouble because gateleen cannot handle such double slashes in its hooking module.

Workaround: Use deprecated 1st generation Paths.

Originating issue is ISAGD-5352 (private issue tracker).

**Comment by nidi3** [comment]
I think this would break usage outside of PISA because BASE_URL normaly does not end with /.
The result would be an url like `http://serverpath` instead of `http://server/path` 

- fix this use case or
- make gateleen accept leading slashes

I'd prefer the second solution because in openAPI files, there's also a leading slash for paths
